### ISSUE TITLE
Comment formatting

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Guess-The-Number-Game#1]
https://github.com/Kelvin-Kwashie/Guess-The-Number-Game/blob/194bacc6aa3998602951cfb92318b7a52e1d15c2/Guess%20the%20number.py#L1

Since you are putting a comment for multiline then better do it properly as well, e.g keep it clean like that:

```
""" 
So this is a code that allows you to guess a number while giving
you clues
"""
```

**Comment by Kelvin-Kwashie** [comment]
I will work on that.

**Comment by chrisK824** [comment]
@Kelvin-Kwashie actually I'm gathering all of code style comments in another issue, closing this one

**Comment by Kelvin-Kwashie** [comment]
Okay
