### ISSUE TITLE
Code readabilty

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Guess-The-Number-Game#2]
There is no golden rule in programming, however here are a few points to keep in mind for better readability:

- Pick a naming convention and stick to it. It doesn't really matter for execution of code  but readability is quite important. For Python the most common naming convention is snake case which looks like that for multi-word names : `my_cool_function` instead of a camel case representation which would be `myCoolFunction`
- Global variables, meaning variables that are defined in main level and not inside functions, loops etc, are usually defined with capital letters. For example, the two variables you have at the very top of your script would be: `NUM_DIGITS`, `MAX_GUESSES`
- docstrings: Not sure you yet know how powerful those are but you still used them in your first project. Make sure to stick with that habbit and always write one for all your functions
- multiline comments: best practice is to separate lines if the comment it's too big. If you are using the triple quote (single or double) make sure to do not include actual comments on the same line as the quotes; it's just better for the eye

Take some time and search for terms:
- code readability: What is it, why is it important? Best practices to achieve it (applies on programming languages)
- variables/functions naming conventions: What is it? Explore alternatives, focus on best practices for Python
- docstrings: What they are? What benefits do they bring? How to do it properly in Python?

After having your fair share of exploring come back and create a branch from this issue to rename your variables/functions and reformat your comments and docstrings.

**Comment by Kelvin-Kwashie** [comment]
Very informative and I have learnt alot

**Comment by Kelvin-Kwashie** [comment]
Thank you very much

**Comment by Kelvin-Kwashie** [comment]
I will resolve all those issues
