### ISSUE TITLE
Name of the script

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Guess-The-Number-Game#3]
For file names stick to words/phrases with no spaces included. Spaces in file or folder names can cause mess and problems, in different ways in each operating system. Also make sure to try and give meaningful names in all of your files based on what they do. It's easier for your and/or others to get a concept of what they are going to read in that code file even before they begin to do so.
So for this case a better suited name would look like this:
`guess_number_name.py`

**Comment by Kelvin-Kwashie** [comment]
Well understood
