### ISSUE TITLE
Code organizing

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Guess-The-Number-Game#4]
When it comes to organizing your code, functions is the way to do it. In short, when something is done more than once, then do it with a function.

That said, there are a few more rules to follow here so that your code is better:
1. Functions shouldn't be too big. The bigger a function gets the more probable that it is doing too many things. As a result the readability decreases. If a function is getting too big then most probably it can be divided into more functions that each one does simpler smaller tasks. Note: Don't excess on it, just use your instict for starters.
2. A function should normally do a simple thing. Sure, one function might do more than a thing, but argument here is that in its concept a function should have a sole purpose.

As an example, in this particular script:
1. function `getClues` should do exactly that, hence give you back clues. So this part of code could have been out of the function:
```
if guess == secretNum:
    return 'You got it!!!'
     
```
this piece of code could have been easily moved out of the function and placed just right after the user gives you an input. Besides you already are doing the same comparison in your main function.
e.g

```
def main():
    print('''Welcome to the 'Guess the number' game
          I will pick a number with 3 digits
          You have 10 guesses
          Here are the clues:
          When I say:        That means:
          Pico               one digit is correct but in a wrong position
          Fermi              one digit is correct and in the right position
          Bagels             no digit is correct''')
    
    while True: #The main game loop
        #This stores the secret number the player needs to guess
        secretNum = getSecretNum()
        print('I have thought of a number.')
        print('You have 10 guesses to get it.')

        numGuesses = 1
        while numGuesses <= 10:
            guess = ''
            #keep looping until they enter a valid guess
            while len(guess) !=  num_digits or not guess.isdecimal():
                print('Guess #{}:'.format(numGuesses))
                guess = input('> ')
     
           if guess == secretNum:
               print( 'You got it!!!')
               break #They're correct so break out of the loop

            clues = getClues(guess, secretNum)
            print(clues)
            numGuesses += 1

            if numGuesses > max_guesses:
                print('Sorry, You ran out of guesses')
                print('The secret number was {}'.format(secretNum))
        #Ask the player if they want to play again
        print('Do you want to play again')
        if not input('> ').lower().startswith('y'):
            break

    print('Thanks for playing!!')

```

**Comment by Kelvin-Kwashie** [comment]
Well understood
